/*
 * SWITCH_error.h
 *
 * Created: 9/18/2022 3:40:35 PM
 *  Author: ammar
 */ 


#ifndef SWITCH_ERROR_H_
#define SWITCH_ERROR_H_

#include "../../1-MCAL/DIO/DIO.h"
#include "../../1-MCAL/INTERRUPT/INTERRUPT.h"
#include "SWITCH_private.h"

#define SWITCH_PIN_ERROR_CHECK(PIN) if (PIN < PIN0 || PIN > PIN7) return SWITCH_PIN_OUT_OF_RANGE
#define SWITCH_PORT_ERROR_CHECK(PORT) if (PORT < PORTA || PORT > PORTD) return SWITCH_PORT_OUT_OF_RANGE
#define SWITCH_INTERRUPT_MODE_ERROR_CHECK(MODE) if (MODE < SWITCH_EXINT_MODE || MODE > SWITCH_PULLING_MODE) return SWITCH_INVALID_INTERRUPT_MODE
#define SWITCH_PULLUP_ERROR_CHECK(PULL) if (PULL < SWITCH_PULLDOWN || PULL > SWITCH_PULLUP)  return SWITCH_INVALID_PULLUP_MODE
#define SWITCH_INTERRUPT_PIN_ERROR_CHECK(PORT, PIN) if (	!(	(PORT != EXINT0_PORT && PIN != EXINT0_PIN) ||	(PORT !=EXINT1_PORT && PIN != EXINT1_PIN)	||	(PORT != EXINT2_PORT && PIN != EXINT2_PIN)	)	) return SWITCH_NOT_AN_INTERRUPT_PIN


#endif /* SWITCH_ERROR_H_ */